<a href="https://colab.research.google.com/github/MarcosRoms/Deep_learning_colab/blob/main/2B_Xor_JCOR_Perceptron_backpropagation_DIPLOMADO_Al.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [3]:
# cargamos las 4 combinaciones de las compuertas XOR
training_data = np.array([[0,0,0,0],[1,0,0,0],[1,1,0,0],[1,1,0,0]])

# y estos son los resultados que se obtienen, en el mismo orden
target_data = np.array([[0],[1],[1],[0],])

In [4]:
print(target_data)

[[0]
 [1]
 [1]
 [0]]


In [5]:
print(training_data)

[[0 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 0 0]]


Definimos una arquitectura de red neuronal

In [6]:
model = Sequential()
model.add(Dense(16, input_dim=4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

# Entrenamiento de la red

In [8]:
model.fit(training_data, target_data , epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - binary_accuracy: 0.5000 - loss: 0.2523
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - binary_accuracy: 0.2500 - loss: 0.2522
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - binary_accuracy: 0.2500 - loss: 0.2519
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - binary_accuracy: 0.2500 - loss: 0.2517
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - binary_accuracy: 0.2500 - loss: 0.2515
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - binary_accuracy: 0.2500 - loss: 0.2513
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - binary_accuracy: 0.2500 - loss: 0.2511
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - binary_accuracy: 0.2500 - loss: 0.2509
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - binary_accuracy: 0.2500 - loss: 0.2508
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - binary_accuracy: 0.5000 - loss: 0.2506
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - binary_accuracy: 0.5000 - loss: 0.2504

In [9]:
# evaluamos el modelo
scores = model.evaluate(training_data, target_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - binary_accuracy: 0.7500 - loss: 0.1524


In [10]:

print (model.predict(training_data).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[[0.]
 [1.]
 [1.]
 [1.]]


# Ejemplo Tarea

In [3]:
X = np.array([
    [0, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 0, 1, 1],
    [0, 1, 0, 0],
    [0, 1, 0, 1],
    [0, 1, 1, 0],
    [0, 1, 1, 1],
    [1, 0, 0, 0],
    [1, 0, 0, 1],
    [1, 0, 1, 0],
    [1, 0, 1, 1],
    [1, 1, 0, 0],
    [1, 1, 0, 1],
    [1, 1, 1, 0],
    [1, 1, 1, 1]
])

y = np.array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1])

In [7]:
model = Sequential()
model.add(Dense(16, input_shape=(4,), activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [9]:
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])


In [10]:
model.fit(X, y, epochs=400)


Epoch 1/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.2576
Epoch 2/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.5000 - loss: 0.2569
Epoch 3/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.2563
Epoch 4/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.2557
Epoch 5/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5625 - loss: 0.2551
Epoch 6/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5625 - loss: 0.2544
Epoch 7/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6250 - loss: 0.2538
Epoch 8/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6250 - loss: 0.2532
Epoch 9/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6250 - loss: 0.2526
Epoch 10/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6250 - loss: 0.2520
Epoch 11/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6250 - loss: 0.2513
Epoch 12/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6250 - los

In [11]:
loss, accuracy = model.evaluate(X, y)
print(f'Loss: {loss}, Accuracy: {accuracy}')


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 294ms/step - accuracy: 1.0000 - loss: 0.0572
Loss: 0.05723138898611069, Accuracy: 1.0


In [12]:
predictions = model.predict(X)
print(predictions.round())


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 226ms/step
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]]


In [13]:
y

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1])

In [16]:
predictions = predictions.round()

In [17]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Supongamos que tienes los siguientes arrays
y_real = y
y_pred = predictions
# Calcular precisión
accuracy = accuracy_score(y_real, y_pred)
print(f'Precisión: {accuracy:.2f}')

# Calcular precisión (precision)
precision = precision_score(y_real, y_pred)
print(f'Precisión (precision): {precision:.2f}')

# Calcular recall
recall = recall_score(y_real, y_pred)
print(f'Recall: {recall:.2f}')

# Calcular f1-score
f1 = f1_score(y_real, y_pred)
print(f'F1-score: {f1:.2f}')

# Calcular matriz de confusión
conf_matrix = confusion_matrix(y_real, y_pred)
print('Matriz de Confusión:')
print(conf_matrix)

Precisión: 1.00
Precisión (precision): 1.00
Recall: 1.00
F1-score: 1.00
Matriz de Confusión:
[[9 0]
 [0 7]]
